name: SPT
channels:
  - defaults
  - conda-forge
dependencies:
  - numpy
  - pandas
  - pytables
  - python=3.7
  - scikit-learn
  - fastparquet
  - trackpy
  - h5py
  - pyyaml
  - pip
  - matplotlib
  - scipy
  - dask
  - hdbscan
  - tqdm
  - pyqt
  - numba
  - spyder
  - colorama
  - jupyterlab
  - snappy
  - trackpy
  - pip:
    - lmfit
    - sphinx-rtd-theme

