name: SPT
channels:
  - defaults
  - conda-forge
dependencies:
  - colorama
  - numpy
  - scikit-learn
  - scipy
  - numba
  - pandas
  - python=3.7
  - pip
  - pyqt
  - h5py
  - jupyterlab
  - pytables
  - tqdm=4.36.1
  - spyder
  - dask
  - fastparquet
  - pyyaml
  - hdbscan
  - matplotlib
  - trackpy
  - pip:
    - lmfit
    - sphinx-rtd-theme

